language: python

dist: precise

python:
    - 3.6 

sudo: required

before_install: 
    - WORKDIR=`pwd`
    - export PATH=$WORKDIR/bin/:$PATH

install:
    ## Python modules
    - pip install cython
    - pip install pysam

    ## Picard
    - wget https://github.com/broadinstitute/picard/releases/download/1.131/picard-tools-1.131.zip
    - unzip picard-tools-1.131.zip

    ## Exonerate
    - git clone https://github.com/adamewing/exonerate.git
    - cd exonerate
    - git checkout v2.4.0
    - autoreconf -i
    - ./configure --prefix=$WORKDIR && make && make install
    - cd ..

    # Velvet
    - wget https://www.ebi.ac.uk/~zerbino/velvet/velvet_1.2.10.tgz
    - tar xvzf velvet_1.2.10.tgz
    - sudo make -C velvet_1.2.10
    - sudo cp velvet_1.2.10/velvetg $WORKDIR/bin/
    - sudo cp velvet_1.2.10/velveth $WORKDIR/bin/

    ## BWA
    - git clone https://github.com/lh3/bwa.git
    - sudo make -C bwa
    - sudo mv bwa/bwa $WORKDIR/bin

    ## HTSLIB
    - git clone https://github.com/samtools/htslib.git
    - sudo make -C htslib

    ## Samtools
    - git clone https://github.com/samtools/samtools.git
    - sudo make -C samtools
    - sudo mv samtools/samtools $WORKDIR/bin/
    - sudo mv samtools/misc/wgsim $WORKDIR/bin/

    ## Bcftools
    - git clone https://github.com/samtools/bcftools.git
    - sudo make -C bcftools
    - sudo mv bcftools/bcftools $WORKDIR/bin

script:
    - python setup.py install
    - cd test
    - ./test_indel.sh ../picard-tools-1.131/picard.jar 
    - ./test_snv.sh ../picard-tools-1.131/picard.jar
    - ./test_sv.sh
